FlowerBouquet/Models/contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FlowerBouquet.Models
{
    public class contact
    {
        [Key]
        public int contactID { get; set; }
        [Required, Display(Name = "Name")]
        public string Name { get; set; }
        [Required, Display(Name = "Email"), EmailAddress]
        public string SenderEmail { get; set; }
        [Required,Display(Name="Contact us")]
        [StringLength(1000,MinimumLength=3)]
        public string Message { get; set; }
        [Display(Name="Upload Image")]
        public string contactImage { get; set; }

    }
}

FlowerBouquet/Controllers/contactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlowerBouquet.Data;
using FlowerBouquet.Models;

namespace FlowerBouquet.Controllers
{
    public class contactsController : Controller
    {
        private FlowerBouquetContext db = new FlowerBouquetContext();

        // GET: contacts
        public ActionResult Index()
        {
           
            return View(db.contacts.ToList());
        }

        // GET: contacts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contact contact = db.contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: contacts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "contactID,Name,SenderEmail,Message,contactImage")] contact contact, HttpPostedFileBase imgfile)
        {
            string path = uploadimage(imgfile);
            if (ModelState.IsValid)
            {
                contact.contactImage = path;
                db.contacts.Add(contact);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return View(contact);
        }
        //method for uploading image
        public string uploadimage(HttpPostedFileBase file)

        {

            Random r = new Random();

            string path = "-1";

            int random = r.Next();

            if (file != null && file.ContentLength > 0)

            {

                string extension = System.IO.Path.GetExtension(file.FileName);

                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))

                {

                    try

                    {



                        path = Path.Combine(Server.MapPath("~/Content/contact"), random + Path.GetFileName(file.FileName));

                        file.SaveAs(path);

                        path = "~/Content/contact/" + random + Path.GetFileName(file.FileName);



                        //    ViewBag.Message = "File uploaded successfully";

                    }

                    catch (Exception ex)

                    {

                        path = "-1";

                    }

                }

                else

                {

                    Response.Write("<script>alert('Only jpg ,jpeg or png formats are acceptable....'); </script>");

                }

            }



            else

            {

                Response.Write("<script>alert('Please select a file'); </script>");

                path = "-1";

            }







            return path;

        }

        // GET: contacts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contact contact = db.contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "contactID,Name,SenderEmail,Message,contactImage")] contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        // GET: contacts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contact contact = db.contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            contact contact = db.contacts.Find(id);
            db.contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FlowerBouquet/Controllers/staticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlowerBouquet.Controllers
{
    public class staticController : Controller
    {
        // GET: static
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult HomePage()
        {
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        public ActionResult Team ()
        {
            return View();
        }
    }
}

FlowerBouquet/Views/contacts/Create.cshtml
@model FlowerBouquet.Models.contact

@{
    ViewBag.Title = "Create";
}

@*<h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>contact</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SenderEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SenderEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SenderEmail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.contactImage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.contactImage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.contactImage, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@





<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link href="~/static/contactstyle.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/3658ab6f9c.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <title>Contact Page</title>

    <style>
        .footer {
            background-color: #F5F5F5;
            color: #8a8a8a;
            font-size: 16px;
            padding: 60px 0 20px;
        }

        .column1 h3 {
            margin-bottom: 20px;
        }

        .app-logo img {
            margin-bottom: 20px;
        }

        .column2 img {
            width: 160px;
        }

        .column3 ul, .column4 ul {
            padding: 0;
        }

            .column3 ul li, .column4 ul li {
                list-style: none;
            }

            .column4 ul li {
                display: inline;
                padding: 0 5px;
            }

        .hr {
            margin: 20px 0;
        }

        .copyright {
            text-align: center;
        }
    </style>
</head>
<body>
    <header style="color:white">
        <div class="container">
            <h1 class="span">Flower Bouquet</h1>
            <hr>
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid g-0">
                    <!--<a class="navbar-brand" href="#">Navbar</a>-->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 menu">
                            <li class="nav-item">
                                @Html.ActionLink("Home", "HomePage", "static")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("AboutUs", "AboutUs", "static")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Shop", "Index", "Userproducts")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Meet the Team", "Index", "Userteams")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Contact", "Create", "contacts")
                            </li>
                          

                        </ul>
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fab fa-facebook-f"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-bell"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-caret-down"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="login.php"><i class="fas fa-user-alt"></i></a>
                            </li>


                        </ul>

                    </div>
                </div>
            </nav>
            <!--menu end-->
        </div>
    </header>
    <!--beginning of form-->

    @using (Html.BeginForm("Create", "contacts", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="Container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h2 class="heading">Get In Touch</h2>
                    <p>Feel Free To Talk With Us</p>
                    <p>flowerBouquet@gmail.com</p>
                    <p>01948984316</p>
                </div>
                <div class="col-sm-12 col-md-4">
                    <form method="POST">
                        <div class="form-group mb-3" data-validate="Name is required">

                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                        </div>
                        <div class="form-group mb-3" data-validate="Valid email is required: ex@abc.xyz">
                            @Html.LabelFor(model => model.SenderEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.SenderEmail, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SenderEmail, "", new { @class = "text-danger" })


                        </div>

                        <div class="form-group mb-3" data-validate="Message is required">
                            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                           

                            @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group mb-3" data-validate="Image is required">
                            @Html.LabelFor(model => model.contactImage, htmlAttributes: new { @class = "control-label col-md-2" })
                            @*@Html.EditorFor(model => model.contactImage, new { htmlAttributes = new { @class = "form-control" } })*@
                            <input type="file" id="imgfile" name="imgfile" class="btn btn-default" />
                            @Html.ValidationMessageFor(model => model.contactImage, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group mb-3">
                            <input type="submit" value="Create" class="btn btn-default" />

                        </div>
                    </form>
                    <div>
                        <p style="font-weight: Bold;">Thanks for Submitting...</p>
                    </div>
                </div>
            </div>
        </div>

    }
    <!--end of form-->

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 column1">
                    <h3>Download Our App</h3>
                    <p>Download Our app for ios and android</p>
                    <div class="app-logo">

                        <img src="~/staticimages/gplay.png" />
                    </div>

                </div>
                <div class="col-lg-3 col-md-6 column2">

                    <img src="~/staticimages/logo.jpg" />
                    <p>It is a long established fact that a reader will be distracted by the readable content </p>
                </div>




                <div class="col-lg-3 col-md-6 column3">
                    <h3>Useful links</h3>
                    <ul>
                        <li>Return Policy</li>
                        <li>Payment Details</li>
                        <li>Use Coupuns</li>
                        <li>Join Affiliate</li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 column4">
                    <h3>Follow us</h3>
                    <ul>
                        <li><i class="fab fa-facebook-f"></i></li>
                        <li><i class="fab fa-twitter"></i></li>
                        <li><i class="fab fa-instagram-square"></i></li>
                        <li><i class="fab fa-linkedin"></i></li>
                    </ul>
                </div>

            </div>

            <hr>
            <p class="copyright">&#169 Copyright 2021.All Rights Reserved</p>
        </div>

    </footer>




    <script src="bootstrap-validate.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>

</html>

FlowerBouquet/Views/contacts/Delete.cshtml
@model FlowerBouquet.Models.contact

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>contact</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SenderEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SenderEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contactImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contactImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FlowerBouquet/Views/contacts/Details.cshtml
@model FlowerBouquet.Models.contact

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>contact</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SenderEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SenderEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contactImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contactImage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.contactID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FlowerBouquet/Views/contacts/Edit.cshtml
@model FlowerBouquet.Models.contact

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>contact</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.contactID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SenderEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SenderEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SenderEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contactImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contactImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contactImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FlowerBouquet/Views/contacts/Index.cshtml
@model IEnumerable<FlowerBouquet.Models.contact>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SenderEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contactImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SenderEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contactImage)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.contactID }) |
            @Html.ActionLink("Details", "Details", new { id=item.contactID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.contactID })
        </td>
    </tr>
}

</table>