FlowerBouquet/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace FlowerBouquet.Models
{
    public class Cart
    {
        [Key]

        public int cartID { get; set; }
        public int productId { get; set; }
        [ForeignKey("productId")]
        public virtual product products { get; set; }
        [Range(typeof(int), "1", "500", ErrorMessage = "Invalid Quantity")]
        public int quantity { get; set; }
        [Required(ErrorMessage = "Please give a valid price")]
        public int price { get; set; }
        public DateTime createdDate { get; set; }
        public virtual ICollection<product> productcollection { get; set; }


    }
}

FlowerBouquet/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlowerBouquet.Data;
using FlowerBouquet.Models;

namespace FlowerBouquet.Controllers
{
    public class CartsController : Controller
    {
        private FlowerBouquetContext db = new FlowerBouquetContext();

        // GET: Carts
        public ActionResult Index()
        {
            var carts = db.Carts.Include(c => c.products);
            return View(carts.ToList());
        }

        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            ViewBag.productId = new SelectList(db.products, "productId", "productName");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cartID,productId,quantity,price,createdDate")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.productId = new SelectList(db.products, "productId", "productName", cart.productId);
            return View(cart);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            ViewBag.productId = new SelectList(db.products, "productId", "productName", cart.productId);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cartID,productId,quantity,price,createdDate")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.productId = new SelectList(db.products, "productId", "productName", cart.productId);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cart cart = db.Carts.Find(id);
            db.Carts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult cartremoveitem(int id)
        {
            Cart cart = db.Carts.Find(id);
            db.Carts.Remove(cart);
            db.SaveChanges();
            return View();


        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FlowerBouquet/Controllers/staticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlowerBouquet.Controllers
{
    public class staticController : Controller
    {
        // GET: static
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult HomePage()
        {
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        public ActionResult Team ()
        {
            return View();
        }
    }
}

FlowerBouquet/Views/Carts/Create.cshtml
@model FlowerBouquet.Models.Cart

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.productId, "productId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("productId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.productId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.createdDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FlowerBouquet/Views/Carts/Delete.cshtml
@model FlowerBouquet.Models.Cart

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.products.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.products.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FlowerBouquet/Views/Carts/Details.cshtml
@model FlowerBouquet.Models.Cart

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Cart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.products.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.products.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.cartID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FlowerBouquet/Views/Carts/Edit.cshtml
@model FlowerBouquet.Models.Cart

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.cartID)

        <div class="form-group">
            @Html.LabelFor(model => model.productId, "productId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("productId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.productId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.createdDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FlowerBouquet/Views/Carts/Index.cshtml
@model IEnumerable<FlowerBouquet.Models.Cart>

@{
    ViewBag.Title = "Index";

}

@*<h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.products.productName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.createdDate)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.products.productName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.createdDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.cartID }) |
                @Html.ActionLink("Details", "Details", new { id=item.cartID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.cartID })
            </td>
        </tr>
    }

    </table>*@



<!--Custom Code-->


<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/3658ab6f9c.js" crossorigin="anonymous"></script>


    <!-- Bootstrap CSS -->

    <link href="~/static/bootstrap.css" rel="stylesheet" />

    <link href="~/static/cartstyle.css" rel="stylesheet" />
    <link href="~/static/media.css" rel="stylesheet" />


    <title>All products</title>
    <!--Style code-->
    <style>
        .footer {
            background-color: #F5F5F5;
            color: #8a8a8a;
            font-size: 16px;
            padding: 60px 0 20px;
        }

        .column1 h3 {
            margin-bottom: 20px;
        }

        .app-logo img {
            margin-bottom: 20px;
        }

        .column2 img {
            width: 160px;
        }

        .column3 ul, .column4 ul {
            padding: 0;
        }

            .column3 ul li, .column4 ul li {
                list-style: none;
            }

            .column4 ul li {
                display: inline;
                padding: 0 5px;
            }

        .hr {
            margin: 20px 0;
        }

        .copyright {
            text-align: center;
        }
    </style>
    <!--style code end-->
</head>
<body>

    <!--header strt-->
    <header>
        <div class="container">
            <h1 class="span">Flower Bouquet</h1>
            <hr>
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid g-0">
                    <!--<a class="navbar-brand" href="#">Navbar</a>-->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 menu custom">
                            <li class="nav-item">
                                @Html.ActionLink("Home", "HomePage", "static")


                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Shop</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">FAQ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Contact</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Meet the Team</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">New Collection</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fab fa-facebook-f"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-bell"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-caret-down"></i></a>
                            </li>

                        </ul>

                    </div>
                </div>
            </nav>
            <!--menu end-->
        </div>
    </header>


    <!--cart table start-->
    <section class="product-table">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total price</th>
                    <th>Remove Item</th>

                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelitem => item.products.productName)</td>
                        <td>@Html.DisplayFor(modelitem => item.price)</td>
                        <td>@Html.DisplayFor(modelitem => item.quantity)</td>
                        @{
                            var price = item.price;
                            var quantity = item.quantity;
                            var totalprice = price * quantity;
                        }
                        <td>@totalprice</td>

                        <td>
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    @*<input type="submit" value="remove" class="btn btn-default" />*@

                                    @Html.ActionLink("Remove", "cartremoveitem", new { id = item.cartID })
                                </div>
                            }


                        </td>

                    </tr>
                }

            </tbody>
        </table>
    </section>


    <!--footer strt-->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 column1">
                    <h3>Download Our App</h3>
                    <p>Download Our app for ios and android</p>
                    <div class="app-logo">

                        <img src="~/staticimages/gplay.png" />
                    </div>

                </div>
                <div class="col-lg-3 col-md-6 column2">

                    <img src="~/staticimages/logo.jpg" />
                    <p>It is a long established fact that a reader will be distracted by the readable content </p>
                </div>




                <div class="col-lg-3 col-md-6 column3">
                    <h3>Useful links</h3>
                    <ul>
                        <li>Return Policy</li>
                        <li>Payment Details</li>
                        <li>Use Coupuns</li>
                        <li>Join Affiliate</li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 column4">
                    <h3>Follow us</h3>
                    <ul>
                        <li><i class="fab fa-facebook-f"></i></li>
                        <li><i class="fab fa-twitter"></i></li>
                        <li><i class="fab fa-instagram-square"></i></li>
                        <li><i class="fab fa-linkedin"></i></li>
                    </ul>
                </div>

            </div>

            <hr>
            <p class="copyright">&#169 Copyright 2021.All Rights Reserved</p>
        </div>

    </footer>
    <!--footer end-->

    <script src="~/static/popper.min.js"></script>
    <script src="~/static/bootstrap.min.js"></script>

    <script src="~/static/script.js"></script>
</body>
</html>

FlowerBouquet/Views/Carts/cartremoveitem.cshtml
@{
    ViewBag.Title = "cartremoveitem";
}


<h2>Item has been removed</h2>
@Html.ActionLink("Back to Cart", "Index", "Carts")